### ISSUE TITLE
As a developer, I want to have collapsible sections

### ISSUE THREAD

**Issue by MGZero** [ZFGCCP/zfgc-ui#5]
Collapsible sections will be needed for various parts of the forum. They should look and work like the sections on:

http://zfgc.com:8080/forum/zfgcui/userprofile?userId=81

Create a new component to replicate this functionality.
It should take the following parameters:

- Section heading (optional)

If no section heading is displayed, then do not make the section collapsible. Just display the body in the template (See sign-in page on zfgc-ui for how this should look).
This component should just wrap the body of the section and apply wrapping divs and styling. 
Styles from the sign-in page should be moved into a new scss file.

**Comment by mvegh1** [comment]
Added 90% of the requirements in my opinion. This was far simpler to implement than anticipated due to react-bootstrap/Accordion.

collapsible.component.js has its body hardcoded right now, and the header either:

1. Shows, but with a title
2. Hides via d-none bootstrap class

There is no scenario yet where the accordion card-header uses an icon rather than text to toggle the card-body
